### ISSUE TITLE
Subscription of other commands

### ISSUE THREAD

**Issue by pachiras** [knledg/elm-local-storage-ports#3]
Hello,

Thank you for sharing the great library.
I'm currently trying to use this, but I need one more functionality.

I have to refresh a list on my app at the timing of the local storage was changed.
Is it possible to subscribe  all the events that the data is changed by storageSetItem, 
storageRemoveItem, etc. except storageGetItem which already has a message.

Thanks.

**Comment by paulstatezny** [comment]
@pachiras, thanks for logging this issue! For some reason I didn't have notifications set up properly with this repository.

That seems like a feature that would be well scoped to this library.

My initial thought is that it would be nice to do something like this:

```elm
subscriptions : Model -> Sub Msg
subscriptions model =
  LocalStorage.storageWatchForChanges "key" ReceiveChanges
```

I'll try to put some thought into it over the next week.

**Comment by janwirth** [comment]
I'm also interested in this use case. I would like to watch some changes from the LS.

**Comment by paulstatezny** [comment]
@pachiras @FranzSkuffka  can you describe your use cases in a little more detail? Specifically, are you interested in watching changes to a single key / subset of keys in local storage? Or are you looking to watch for changes in any/every key?

**Comment by paulstatezny** [comment]
@pachiras @FranzSkuffka I added this feature in the form of 3 new subscriptions:

```
storageOnKeyAdded
storageOnKeyRemoved
storageOnKeyChanged
```

The docs start here:

https://github.com/paulstatezny/elm-local-storage-ports/blob/master/API.md#storageonkeyadded

Here's an example repo with how to use them: https://github.com/paulstatezny/example-elm-local-storage-ports-app

Here's Main.elm: https://github.com/paulstatezny/example-elm-local-storage-ports-app/blob/master/src/Main.elm

(You'll have to run something like https://www.npmjs.com/package/http-server to see it in action, because `file:///` URLs won't emit `StorageEvent` events.)

Do you have any feedback?

**Comment by paulstatezny** [comment]
I'll close this issue since I added the feature. If you have any feedback feel free to comment here or open another issue. Thanks!
